In [1]:
try:
    from configuracoes_notebooks import set_proj_dir
    set_proj_dir()
except:
    from teste import diretorio_teste
    diretorio_teste()

O diretorio do seu projeto é coleta_cebrap
Caminho absoluto do diretorio encontrado C:\Users\Olívia\Desktop\batatinhas\coleta_cebrap
Caminho no path.

In [2]:
import geopandas as gpd
import os

from notebooks.jupyter import utils
from utils import (
    get_data_diretorio,
    save_parquet_excel,
)

# Ocorrências de Inundações / Área do Distritos

In [3]:
data_path = get_data_diretorio()
assets_path = os.path.join(
    data_path,
    'assets'
)

# Dependências
Este notebook é dependente do arquivo resultante do notebok '.alaga_por_dist'

In [4]:
gdf_distritos = gpd.read_parquet(
    os.path.join(
        assets_path,
        'areas_alagamento',
        'qt_ocorrencias_alaga_distrito.parquet'
    )
)

In [5]:
gdf_distritos.sample(3)

,CD_MUN,NM_MUN,CD_DIST,NM_DIST,CD_RGINT,NM_RGINT,CD_RGI,NM_RGI,CD_CONCURB,NM_CONCURB,AREA_KM2,total_pop,total_dom,geometry,qt_alaga_ocor
47,3550308,São Paulo,355030848,LAPA,3501,São Paulo,350001,São Paulo,3550308,São Paulo/SP,10.275987,75533,36633,"POLYGON ((326041.802 7395647.087, 325996.785 7...",1.0
42,3550308,São Paulo,355030843,JARDIM ANGELA,3501,São Paulo,350001,São Paulo,3550308,São Paulo/SP,36.738281,311432,125669,"POLYGON ((318894.224 7372253.527, 318886.412 7...",2.0
1,3550308,São Paulo,355030802,ALTO DE PINHEIROS,3501,São Paulo,350001,São Paulo,3550308,São Paulo/SP,7.496479,37359,17931,"POLYGON ((326909.968 7394207.048, 326887.264 7...",0.0

# Cálculo

In [6]:
gdf_distritos['inund_por_area'] = (
    gdf_distritos['qt_alaga_ocor'] / gdf_distritos['geometry'].area
)

# Padronização de Entrega

In [7]:
gdf_distritos.columns

Index(['CD_MUN', 'NM_MUN', 'CD_DIST', 'NM_DIST', 'CD_RGINT', 'NM_RGINT',
       'CD_RGI', 'NM_RGI', 'CD_CONCURB', 'NM_CONCURB', 'AREA_KM2', 'total_pop',
       'total_dom', 'geometry', 'qt_alaga_ocor', 'inund_por_area'],
      dtype='object')

In [8]:
drop_cols={
    'CD_MUN',
    'NM_MUN',
    'CD_RGINT',
    'NM_RGINT',
    'CD_RGI',
    'NM_RGI',
    'CD_CONCURB',
    'NM_CONCURB',
    'AREA_KM2',
    'geometry'
}

gdf_distritos.drop(
    columns=drop_cols,
    axis=1,
    inplace=True
)

In [9]:
gdf_distritos.sample(2)

      CD_DIST     NM_DIST  total_pop total_dom  qt_alaga_ocor  inund_por_area
53  355030854     MORUMBI      43690     20710            0.0    0.000000e+00
14  355030815  CAMPO BELO      71034     36663            3.0    3.392900e-07

In [10]:
gdf_distritos.set_index('NM_DIST', inplace=True)

In [11]:
gdf_distritos.sample(2)

              CD_DIST  total_pop total_dom  qt_alaga_ocor  inund_por_area
NM_DIST
SAO MIGUEL  355030874      81011     33222           11.0        0.000001
REPUBLICA   355030866      60825     42899            0.0        0.000000

# Salvar GDF

In [12]:
save_parquet_excel(
    gdf_distritos,
    fname='alagamento_por_area_distrito',
    data_path = assets_path,
    data_subpath = 'areas_alagamento'
)