In [1]:
from configuracoes_notebooks import set_proj_dir
set_proj_dir()

O diretorio do seu projeto é coleta_cebrap
Caminho absoluto do diretorio encontrado C:\Users\x526378\Desktop\projetos\cebrap\coleta_cebrap
Caminho no path.

In [2]:
from notebooks.jupyter import utils
from utils import (
    get_data_diretorio,
    check_crs,
    save_parquet_excel
)
from utils.downloads import download_malha_geosampa

# Mancha de Inundação (25 anos)

In [3]:
data_path= get_data_diretorio()

In [4]:
gdf_mancha_inundacao2=download_malha_geosampa('mancha_inundacao_25',
                                             data_path)

helloo
C:\Users\x526378\Desktop\projetos\cebrap\coleta_cebrap\data\cache\mancha_inundacao_25.zip

In [5]:
gdf_mancha_inundacao2.shape

(30000, 11)

In [6]:
gdf_mancha_inundacao=download_malha_geosampa(
    'mancha_inundacao_25',
    data_path,
    True
)

Cuidado que talvez voce precise definir uma coluna de indice. A API retorna um documento com um erro e não dá status code correto!
Carregando arquivo em cache

In [7]:
gdf_mancha_inundacao.shape

(304724, 11)

In [8]:
gdf_mancha_inundacao.sample(2)

,cd_identif,nm_bacia_h,qt_area_me,qt_elevaca,qt_cota_in,qt_profund,cd_usuario,qt_tempo_r,dt_atualiz,sg_fonte_o,geometry
192538,391027,Sapateiro,86.6,722.882,722.93,0.05,None,25,2024-08-23,FCTH,"POLYGON ((327902.272 7390211.798, 327902.272 7..."
47652,246141,Água Vermelha e Lajeado,86.6,728.532,730.17,1.64,None,25,2024-08-23,FCTH,"POLYGON ((355558.024 7402808.92, 355553.024 74..."

In [9]:
gdf_mancha_inundacao.columns

Index(['cd_identif', 'nm_bacia_h', 'qt_area_me', 'qt_elevaca', 'qt_cota_in',
       'qt_profund', 'cd_usuario', 'qt_tempo_r', 'dt_atualiz', 'sg_fonte_o',
       'geometry'],
      dtype='object')

Acredito que o indicador esteja se referindo apenas à área(m²) de inundação no território, mas considerando as informações de elevação, profundidade, cota de inundação* e tempo de retorno, é possível fazer análises e cálculos mais aprofundados.

*Cota de Inundação: "As cotas de inundação são valores que indicam níveis de água, que se
encontram em posições discretas sobre os rios e que são obtidas por modelos hidrodinâmicos,
estacas, sensores etc." ([ROSIM, s/d, p.2](https://files.abrhidro.org.br/Eventos/Trabalhos/154/168.pdf)).

O tempo de retorno poderia ser uma informação interessante, mas TODOS constam como 25 (anos, provavelmente), então provavelmente se refere a algo que não tempo médio de retorno da ocorrência. O mesmo vale para data de atualização.

# Padronização de nomes

In [11]:
drop_cols={
    'cd_usuario', 
    'sg_fonte_o', 
    'qt_tempo_r', 
    'dt_atualiz'
}

gdf_mancha_inundacao.rename({'cd_identif':'cd_mancha_inund'}, axis=1, inplace=True)
gdf_mancha_inundacao.drop(columns=drop_cols, axis=1, inplace=True)

In [12]:
gdf_mancha_inundacao.sample(2)

,cd_mancha_inund,nm_bacia_h,qt_area_me,qt_elevaca,qt_cota_in,qt_profund,geometry
271704,470193,Cordeiro,21.65,758.661,759.04,0.38,"POLYGON ((331697.317 7381582.589, 331697.317 7..."
122361,320850,Itaquera,21.65,749.706,749.90,0.19,"POLYGON ((355855.843 7395774.842, 355855.843 7..."

# Conferir CRS

In [13]:
gdf_mancha_inundacao = check_crs(gdf_mancha_inundacao)

# Salvar GDF

In [ ]:
save_parquet_excel(
    gdf_mancha_inundacao,
    'mancha_inundacao_25',
    data_path,
    data_subpath= 'assets'
)