In [1]:
try:
    from configuracoes_notebooks import set_proj_dir
    set_proj_dir()
except:
    from teste import diretorio_teste
    diretorio_teste()

O diretorio do seu projeto é coleta_cebrap
D:\Documentos_Novo\ADPPSP\2024\cebrap\coleta_cebrap

In [2]:
import geopandas as gpd
import os

from notebooks.jupyter import utils
from utils import (
    get_data_diretorio,
    check_crs,
    save_parquet_excel
)

# Ocorrências em 2024

Estávamos usando as manchas de inundação (2025), mas como se tratava de uma previsão para daqui a 25 anos, não fazia sentido usar. Optaram por substituí-la pelos pontos de ocorrência.

Mas as informações que vem da malha de pontos de ocorrência de inundação são referentes apenas a janeiro e fevereiro de 2025.

Por conta disso, optamos por utilizar o shapefile das ocorrências da Proteção e Defesa Civil, no ano de 2024, disponível em:  [GEOSAMPA/'Download de arquivos': representado por uma imagem de SP com uma seta pra baixo)/Proteção e Defesa Civil/Ocorrencias](https://geosampa.prefeitura.sp.gov.br/PaginasPublicas/downloadIfr.aspx?orig=DownloadCamadas&arq=07_Prote%E7%E3o%20e%20Defesa%20Civil%5C%5COcorrencias%5C%5CShapefile%5C%5CSIRGAS_SHP_riscoocorrencia&arqTipo=Shapefile)

In [3]:
data_path = get_data_diretorio()

# Importar dados

In [4]:
gdf_ocorrencias = gpd.read_file(
    os.path.join(
        data_path,
        'manual_download',
        'SIRGAS_SHP_riscoocorrencia_2024'
    )
)

In [5]:
gdf_ocorrencias.explore()

In [6]:
gdf_ocorrencias.sample(2)

,data,ocorrencia,subpreit,name,geometry
1227,2024-02-24,QUEDA DE ARVORE,CS - CAPELA DO SOCORRO,32223672,POINT (327734.492 7368962.885)
4493,2024-01-22,QUEDA DE ARVORE,AD - CIDADE ADEMAR,31996443,POINT (331404.646 7381288.404)

In [7]:
gdf_ocorrencias.shape

(4736, 5)

# Padronizaçã de colunas

A coluna 'name' está claramente sendo usada como chave primária. Que, por padrão, tem 'cd' ou 'id' como identificador.

Para confirmar se realmente é um identificador confiável, veremos se é uma linha com valores únicos:

In [8]:
gdf_ocorrencias.rename(
    columns={
        'name' : 'id_ocorrencias'
    },
    inplace=True
)

In [9]:
gdf_ocorrencias.sample(2)

,data,ocorrencia,subpreit,id_ocorrencias,geometry
784,2024-09-17,QUEDA DE ARVORE,CS - CAPELA DO SOCORRO,33382561,POINT (324606.365 7375023.293)
1795,2024-10-15,QUEDA DE ARVORE,CL - CAMPO LIMPO,33536587,POINT (317761.335 7384273.238)

# Conferir CRS

In [10]:
gdf_ocorrencias=check_crs(gdf_ocorrencias)

O crs do gdf não está correto:None

ValueError: Cannot transform naive geometries.  Please set a crs on the object first.

# Salvar GDF

In [ ]:
save_parquet_excel(
    gdf_ocorrencias, 
    fname= 'ocorrencias_2024',
    data_path = data_path,
    data_subpath = 'assets'
)